#include "ad.xpm"
#include "ae.xpm"
#include "af.xpm"
#include "ag.xpm"
#include "ai.xpm"
#include "al.xpm"
#include "am.xpm"
#include "an.xpm"
#include "ao.xpm"
#include "aq.xpm"
#include "ar.xpm"
#include "as.xpm"
#include "at.xpm"
#include "au.xpm"
#include "aw.xpm"
#include "ax.xpm"
#include "az.xpm"
#include "ba.xpm"
#include "bb.xpm"
#include "bd.xpm"
#include "be.xpm"
#include "bf.xpm"
#include "bg.xpm"
#include "bh.xpm"
#include "bi.xpm"
#include "bj.xpm"
#include "bm.xpm"
#include "bn.xpm"
#include "bo.xpm"
#include "br.xpm"
#include "bs.xpm"
#include "bt.xpm"
#include "bv.xpm"
#include "bw.xpm"
#include "by.xpm"
#include "bz.xpm"
#include "ca.xpm"
#include "cc.xpm"
#include "cd.xpm"
#include "cf.xpm"
#include "cg.xpm"
#include "ch.xpm"
#include "ci.xpm"
#include "ck.xpm"
#include "cl.xpm"
#include "cm.xpm"
#include "cn.xpm"
#include "co.xpm"
#include "cr.xpm"
#include "cs.xpm"
#include "cu.xpm"
#include "cv.xpm"
#include "cx.xpm"
#include "cy.xpm"
#include "cz.xpm"
#include "de.xpm"
#include "dj.xpm"
#include "dk.xpm"
#include "dm.xpm"
#include "do.xpm"
#include "dz.xpm"
#include "ec.xpm"
#include "ee.xpm"
#include "eg.xpm"
#include "eh.xpm"
#include "er.xpm"
#include "es.xpm"
#include "et.xpm"
#include "fi.xpm"
#include "fj.xpm"
#include "fk.xpm"
#include "fm.xpm"
#include "fo.xpm"
#include "fr.xpm"
#include "fx.xpm"
#include "ga.xpm"
#include "gb.xpm"
#include "gd.xpm"
#include "ge.xpm"
#include "gf.xpm"
#include "gg.xpm"
#include "gh.xpm"
#include "gi.xpm"
#include "gl.xpm"
#include "gm.xpm"
#include "gn.xpm"
#include "gp.xpm"
#include "gq.xpm"
#include "gr.xpm"
#include "gs.xpm"
#include "gt.xpm"
#include "gu.xpm"
#include "gw.xpm"
#include "gy.xpm"
#include "hk.xpm"
#include "hm.xpm"
#include "hn.xpm"
#include "hr.xpm"
#include "ht.xpm"
#include "hu.xpm"
#include "id.xpm"
#include "ie.xpm"
#include "il.xpm"
#include "in.xpm"
#include "io.xpm"
#include "iq.xpm"
#include "ir.xpm"
#include "is.xpm"
#include "it.xpm"
#include "je.xpm"
#include "jm.xpm"
#include "jo.xpm"
#include "jp.xpm"
#include "ke.xpm"
#include "kg.xpm"
#include "kh.xpm"
#include "ki.xpm"
#include "km.xpm"
#include "kn.xpm"
#include "kp.xpm"
#include "kr.xpm"
#include "kw.xpm"
#include "ky.xpm"
#include "kz.xpm"
#include "la.xpm"
#include "lb.xpm"
#include "lc.xpm"
#include "li.xpm"
#include "lk.xpm"
#include "lr.xpm"
#include "ls.xpm"
#include "lt.xpm"
#include "lu.xpm"
#include "lv.xpm"
#include "ly.xpm"
#include "ma.xpm"
#include "mc.xpm"
#include "md.xpm"
#include "me.xpm"
#include "mg.xpm"
#include "mh.xpm"
#include "mk.xpm"
#include "ml.xpm"
#include "mm.xpm"
#include "mn.xpm"
#include "mo.xpm"
#include "mp.xpm"
#include "mq.xpm"
#include "mr.xpm"
#include "ms.xpm"
#include "mt.xpm"
#include "mu.xpm"
#include "mv.xpm"
#include "mw.xpm"
#include "mx.xpm"
#include "my.xpm"
#include "mz.xpm"
#include "na.xpm"
#include "nc.xpm"
#include "ne.xpm"
#include "nf.xpm"
#include "ng.xpm"
#include "ni.xpm"
#include "nl.xpm"
#include "no.xpm"
#include "np.xpm"
#include "nr.xpm"
#include "nu.xpm"
#include "nz.xpm"
#include "om.xpm"
#include "pa.xpm"
#include "pe.xpm"
#include "pf.xpm"
#include "pg.xpm"
#include "ph.xpm"
#include "pk.xpm"
#include "pl.xpm"
#include "pm.xpm"
#include "pn.xpm"
#include "pr.xpm"
#include "ps.xpm"
#include "pt.xpm"
#include "pw.xpm"
#include "py.xpm"
#include "qa.xpm"
#include "re.xpm"
#include "ro.xpm"
#include "rs.woa.xpm"
#include "rs.xpm"
#include "ru.xpm"
#include "rw.xpm"
#include "sa.xpm"
#include "sb.xpm"
#include "sc.xpm"
#include "sd.xpm"
#include "se.xpm"
#include "sg.xpm"
#include "sh.xpm"
#include "si.xpm"
#include "sj.xpm"
#include "sk.xpm"
#include "sl.xpm"
#include "sm.xpm"
#include "sn.xpm"
#include "so.xpm"
#include "sr.xpm"
#include "st.xpm"
#include "sv.xpm"
#include "sy.xpm"
#include "sz.xpm"
#include "tc.xpm"
#include "td.xpm"
#include "tf.xpm"
#include "tg.xpm"
#include "th.xpm"
#include "tj.xpm"
#include "tk.xpm"
#include "tl.xpm"
#include "tm.xpm"
#include "tn.xpm"
#include "to.xpm"
#include "tp.xpm"
#include "tr.xpm"
#include "tt.xpm"
#include "tv.xpm"
#include "tw.xpm"
#include "tz.xpm"
#include "ua.xpm"
#include "ug.xpm"
#include "um.xpm"
#include "unknown.xpm"
#include "us.xpm"
#include "uy.xpm"
#include "uz.xpm"
#include "va.xpm"
#include "vc.xpm"
#include "ve.xpm"
#include "vg.xpm"
#include "vi.xpm"
#include "vn.xpm"
#include "vu.xpm"
#include "wf.xpm"
#include "ws.xpm"
#include "ye.xpm"
#include "yt.xpm"
#include "yu.xpm"
#include "za.xpm"
#include "zm.xpm"
#include "zw.xpm"

static char **flags[] =
{
    ad_xpm,ae_xpm,af_xpm,ag_xpm,ai_xpm,al_xpm,am_xpm,an_xpm,ao_xpm,aq_xpm,ar_xpm,
    as_xpm,at_xpm,au_xpm,aw_xpm,ax_xpm,az_xpm,ba_xpm,bb_xpm,bd_xpm,be_xpm,bf_xpm,
    bg_xpm,bh_xpm,bi_xpm,bj_xpm,bm_xpm,bn_xpm,bo_xpm,br_xpm,bs_xpm,bt_xpm,bv_xpm,
    bw_xpm,by_xpm,bz_xpm,ca_xpm,cc_xpm,cd_xpm,cf_xpm,cg_xpm,ch_xpm,ci_xpm,ck_xpm,
    cl_xpm,cm_xpm,cn_xpm,co_xpm,cr_xpm,cs_xpm,cu_xpm,cv_xpm,cx_xpm,cy_xpm,cz_xpm,
    de_xpm,dj_xpm,dk_xpm,dm_xpm,do_xpm,dz_xpm,ec_xpm,ee_xpm,eg_xpm,eh_xpm,er_xpm,
    es_xpm,et_xpm,fi_xpm,fj_xpm,fk_xpm,fm_xpm,fo_xpm,fr_xpm,fx_xpm,ga_xpm,gb_xpm,
    gd_xpm,ge_xpm,gf_xpm,gg_xpm,gh_xpm,gi_xpm,gl_xpm,gm_xpm,gn_xpm,gp_xpm,gq_xpm,
    gr_xpm,gs_xpm,gt_xpm,gu_xpm,gw_xpm,gy_xpm,hk_xpm,hm_xpm,hn_xpm,hr_xpm,ht_xpm,
    hu_xpm,id_xpm,ie_xpm,il_xpm,in_xpm,io_xpm,iq_xpm,ir_xpm,is_xpm,it_xpm,je_xpm,
    jm_xpm,jo_xpm,jp_xpm,ke_xpm,kg_xpm,kh_xpm,ki_xpm,km_xpm,kn_xpm,kp_xpm,kr_xpm,
    kw_xpm,ky_xpm,kz_xpm,la_xpm,lb_xpm,lc_xpm,li_xpm,lk_xpm,lr_xpm,ls_xpm,lt_xpm,
    lu_xpm,lv_xpm,ly_xpm,ma_xpm,mc_xpm,md_xpm,me_xpm,mg_xpm,mh_xpm,mk_xpm,ml_xpm,
    mm_xpm,mn_xpm,mo_xpm,mp_xpm,mq_xpm,mr_xpm,ms_xpm,mt_xpm,mu_xpm,mv_xpm,mw_xpm,
    mx_xpm,my_xpm,mz_xpm,na_xpm,nc_xpm,ne_xpm,nf_xpm,ng_xpm,ni_xpm,nl_xpm,no_xpm,
    np_xpm,nr_xpm,nu_xpm,nz_xpm,om_xpm,pa_xpm,pe_xpm,pf_xpm,pg_xpm,ph_xpm,pk_xpm,
    pl_xpm,pm_xpm,pn_xpm,pr_xpm,ps_xpm,pt_xpm,pw_xpm,py_xpm,qa_xpm,re_xpm,ro_xpm,
    rs_woa_xpm,rs_xpm,ru_xpm,rw_xpm,sa_xpm,sb_xpm,sc_xpm,sd_xpm,se_xpm,sg_xpm,sh_xpm,
    si_xpm,sj_xpm,sk_xpm,sl_xpm,sm_xpm,sn_xpm,so_xpm,sr_xpm,st_xpm,sv_xpm,sy_xpm,
    sz_xpm,tc_xpm,td_xpm,tf_xpm,tg_xpm,th_xpm,tj_xpm,tk_xpm,tl_xpm,tm_xpm,tn_xpm,
    to_xpm,tp_xpm,tr_xpm,tt_xpm,tv_xpm,tw_xpm,tz_xpm,ua_xpm,ug_xpm,um_xpm,unknown_xpm,
    us_xpm,uy_xpm,uz_xpm,va_xpm,vc_xpm,ve_xpm,vg_xpm,vi_xpm,vn_xpm,vu_xpm,wf_xpm,
    ws_xpm,ye_xpm,yt_xpm,yu_xpm,za_xpm,zm_xpm,zw_xpm
};

static char *codes[] =
{
    "ad","ae","af","ag","ai","al","am","an","ao","aq","ar",
    "as","at","au","aw","ax","az","ba","bb","bd","be","bf",
    "bg","bh","bi","bj","bm","bn","bo","br","bs","bt","bv",
    "bw","by","bz","ca","cc","cd","cf","cg","ch","ci","ck",
    "cl","cm","cn","co","cr","cs","cu","cv","cx","cy","cz",
    "de","dj","dk","dm","do","dz","ec","ee","eg","eh","er",
    "es","et","fi","fj","fk","fm","fo","fr","fx","ga","gb",
    "gd","ge","gf","gg","gh","gi","gl","gm","gn","gp","gq",
    "gr","gs","gt","gu","gw","gy","hk","hm","hn","hr","ht",
    "hu","id","ie","il","in","io","iq","ir","is","it","je",
    "jm","jo","jp","ke","kg","kh","ki","km","kn","kp","kr",
    "kw","ky","kz","la","lb","lc","li","lk","lr","ls","lt",
    "lu","lv","ly","ma","mc","md","me","mg","mh","mk","ml",
    "mm","mn","mo","mp","mq","mr","ms","mt","mu","mv","mw",
    "mx","my","mz","na","nc","ne","nf","ng","ni","nl","no",
    "np","nr","nu","nz","om","pa","pe","pf","pg","ph","pk",
    "pl","pm","pn","pr","ps","pt","pw","py","qa","re","ro",
    "rs.woa","rs","ru","rw","sa","sb","sc","sd","se","sg","sh",
    "si","sj","sk","sl","sm","sn","so","sr","st","sv","sy",
    "sz","tc","td","tf","tg","th","tj","tk","tl","tm","tn",
    "to","tp","tr","tt","tv","tw","tz","ua","ug","um","unknown",
    "us","uy","uz","va","vc","ve","vg","vi","vn","vu","wf",
    "ws","ye","yt","yu","za","zm","zw"
};
