/***************************************************************************
 *   Copyright (C) 2007 -2009 by Glen Masgai                               *
 *   mimosius@users.sourceforge.net                                        *
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 *   This program is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
 *   GNU General Public License for more details.                          *
 *                                                                         *
 *   You should have received a copy of the GNU General Public License     *
 *   along with this program; if not, write to the                         *
 *   Free Software Foundation, Inc.,                                       *
 *   59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.             *
 ***************************************************************************/

#ifndef CSLLICENSE_H
#define CSLLICENSE_H

/**
    @author Glen Masgai <mimosius@users.sourceforge.net>
*/

const wxChar *csl_license=wxT(\
                              "            GNU GENERAL PUBLIC LICENSE\n"
                              _L_"                    Version 2, June 1991\n"
                              _L_"\n"
                              _L_" Copyright (C) 1989, 1991 Free Software Foundation, Inc.\n"
                              _L_"                       59 Temple Place, Suite 330, Boston, MA  02111-1307  USA\n"
                              _L_" Everyone is permitted to copy and distribute verbatim copies\n"
                              _L_" of this license document, but changing it is not allowed.\n"
                              _L_"\n"
                              _L_"                Preamble\n"
                              _L_"\n"
                              _L_"  The licenses for most software are designed to take away your\n"
                              _L_"freedom to share and change it.  By contrast, the GNU General Public\n"
                              _L_"License is intended to guarantee your freedom to share and change free\n"
                              _L_"software--to make sure the software is free for all its users.  This\n"
                              _L_"General Public License applies to most of the Free Software\n"
                              _L_"Foundation's software and to any other program whose authors commit to\n"
                              _L_"using it.  (Some other Free Software Foundation software is covered by\n"
                              _L_"the GNU Library General Public License instead.)  You can apply it to\n"
                              _L_"your programs, too.\n"
                              _L_"\n"
                              _L_"  When we speak of free software, we are referring to freedom, not\n"
                              _L_"price.  Our General Public Licenses are designed to make sure that you\n"
                              _L_"have the freedom to distribute copies of free software (and charge for\n"
                              _L_"this service if you wish), that you receive source code or can get it\n"
                              _L_"if you want it, that you can change the software or use pieces of it\n"
                              _L_"in new free programs; and that you know you can do these things.\n"
                              _L_"\n"
                              _L_"  To protect your rights, we need to make restrictions that forbid\n"
                              _L_"anyone to deny you these rights or to ask you to surrender the rights.\n"
                              _L_"These restrictions translate to certain responsibilities for you if you\n"
                              _L_"distribute copies of the software, or if you modify it.\n"
                              _L_"\n"
                              _L_"  For example, if you distribute copies of such a program, whether\n"
                              _L_"gratis or for a fee, you must give the recipients all the rights that\n"
                              _L_"you have.  You must make sure that they, too, receive or can get the\n"
                              _L_"source code.  And you must show them these terms so they know their\n"
                              _L_"rights.\n"
                              _L_"\n"
                              _L_"  We protect your rights with two steps: (1) copyright the software, and\n"
                              _L_"(2) offer you this license which gives you legal permission to copy,\n"
                              _L_"distribute and/or modify the software.\n"
                              _L_"\n"
                              _L_"  Also, for each author's protection and ours, we want to make certain\n"
                              _L_"that everyone understands that there is no warranty for this free\n"
                              _L_"software.  If the software is modified by someone else and passed on, we\n"
                              _L_"want its recipients to know that what they have is not the original, so\n"
                              _L_"that any problems introduced by others will not reflect on the original\n"
                              _L_"authors' reputations.\n"
                              _L_"\n"
                              _L_"  Finally, any free program is threatened constantly by software\n"
                              _L_"patents.  We wish to avoid the danger that redistributors of a free\n"
                              _L_"program will individually obtain patent licenses, in effect making the\n"
                              _L_"program proprietary.  To prevent this, we have made it clear that any\n"
                              _L_"patent must be licensed for everyone's free use or not licensed at all.\n"
                              _L_"\n"
                              _L_"  The precise terms and conditions for copying, distribution and\n"
                              _L_"modification follow.\n"
                              _L_"\n"
                              _L_"            GNU GENERAL PUBLIC LICENSE\n"
                              _L_"   TERMS AND CONDITIONS FOR COPYING, DISTRIBUTION AND MODIFICATION\n"
                              _L_"\n"
                              _L_"  0. This License applies to any program or other work which contains\n"
                              _L_"a notice placed by the copyright holder saying it may be distributed\n"
                              _L_"under the terms of this General Public License.  The \"Program\", below,\n"
                              _L_"refers to any such program or work, and a \"work based on the Program\"\n"
                              _L_"means either the Program or any derivative work under copyright law:\n"
                              _L_"that is to say, a work containing the Program or a portion of it,\n"
                              _L_"either verbatim or with modifications and/or translated into another\n"
                              _L_"language.  (Hereinafter, translation is included without limitation in\n"
                              _L_"the term \"modification\".)  Each licensee is addressed as \"you\".\n"
                              _L_"\n"
                              _L_"Activities other than copying, distribution and modification are not\n"
                              _L_"covered by this License; they are outside its scope.  The act of\n"
                              _L_"running the Program is not restricted, and the output from the Program\n"
                              _L_"is covered only if its contents constitute a work based on the\n"
                              _L_"Program (independent of having been made by running the Program).\n"
                              _L_"Whether that is true depends on what the Program does.\n"
                              _L_"\n"
                              _L_"  1. You may copy and distribute verbatim copies of the Program's\n"
                              _L_"source code as you receive it, in any medium, provided that you\n"
                              _L_"conspicuously and appropriately publish on each copy an appropriate\n"
                              _L_"copyright notice and disclaimer of warranty; keep intact all the\n"
                              _L_"notices that refer to this License and to the absence of any warranty;\n"
                              _L_"and give any other recipients of the Program a copy of this License\n"
                              _L_"along with the Program.\n"
                              _L_"\n"
                              _L_"You may charge a fee for the physical act of transferring a copy, and\n"
                              _L_"you may at your option offer warranty protection in exchange for a fee.\n"
                              _L_"\n"
                              _L_"  2. You may modify your copy or copies of the Program or any portion\n"
                              _L_"of it, thus forming a work based on the Program, and copy and\n"
                              _L_"distribute such modifications or work under the terms of Section 1\n"
                              _L_"above, provided that you also meet all of these conditions:\n"
                              _L_"\n"
                              _L_"    a) You must cause the modified files to carry prominent notices\n"
                              _L_"    stating that you changed the files and the date of any change.\n"
                              _L_"\n"
                              _L_"    b) You must cause any work that you distribute or publish, that in\n"
                              _L_"    whole or in part contains or is derived from the Program or any\n"
                              _L_"    part thereof, to be licensed as a whole at no charge to all third\n"
                              _L_"    parties under the terms of this License.\n"
                              _L_"\n"
                              _L_"    c) If the modified program normally reads commands interactively\n"
                              _L_"    when run, you must cause it, when started running for such\n"
                              _L_"    interactive use in the most ordinary way, to print or display an\n"
                              _L_"    announcement including an appropriate copyright notice and a\n"
                              _L_"    notice that there is no warranty (or else, saying that you provide\n"
                              _L_"    a warranty) and that users may redistribute the program under\n"
                              _L_"    these conditions, and telling the user how to view a copy of this\n"
                              _L_"    License.  (Exception: if the Program itself is interactive but\n"
                              _L_"    does not normally print such an announcement, your work based on\n"
                              _L_"    the Program is not required to print an announcement.)\n"
                              _L_"\n"
                              _L_"These requirements apply to the modified work as a whole.  If\n"
                              _L_"identifiable sections of that work are not derived from the Program,\n"
                              _L_"and can be reasonably considered independent and separate works in\n"
                              _L_"themselves, then this License, and its terms, do not apply to those\n"
                              _L_"sections when you distribute them as separate works.  But when you\n"
                              _L_"distribute the same sections as part of a whole which is a work based\n"
                              _L_"on the Program, the distribution of the whole must be on the terms of\n"
                              _L_"this License, whose permissions for other licensees extend to the\n"
                              _L_"entire whole, and thus to each and every part regardless of who wrote it.\n"
                              _L_"\n"
                              _L_"Thus, it is not the intent of this section to claim rights or contest\n"
                              _L_"your rights to work written entirely by you; rather, the intent is to\n"
                              _L_"exercise the right to control the distribution of derivative or\n"
                              _L_"collective works based on the Program.\n"
                              _L_"\n"
                              _L_"In addition, mere aggregation of another work not based on the Program\n"
                              _L_"with the Program (or with a work based on the Program) on a volume of\n"
                              _L_"a storage or distribution medium does not bring the other work under\n"
                              _L_"the scope of this License.\n"
                              _L_"\n"
                              _L_"  3. You may copy and distribute the Program (or a work based on it,\n"
                              _L_"under Section 2) in object code or executable form under the terms of\n"
                              _L_"Sections 1 and 2 above provided that you also do one of the following:\n"
                              _L_"\n"
                              _L_"    a) Accompany it with the complete corresponding machine-readable\n"
                              _L_"    source code, which must be distributed under the terms of Sections\n"
                              _L_"    1 and 2 above on a medium customarily used for software interchange; or,\n"
                              _L_"\n"
                              _L_"    b) Accompany it with a written offer, valid for at least three\n"
                              _L_"    years, to give any third party, for a charge no more than your\n"
                              _L_"    cost of physically performing source distribution, a complete\n"
                              _L_"    machine-readable copy of the corresponding source code, to be\n"
                              _L_"    distributed under the terms of Sections 1 and 2 above on a medium\n"
                              _L_"    customarily used for software interchange; or,\n"
                              _L_"\n"
                              _L_"    c) Accompany it with the information you received as to the offer\n"
                              _L_"    to distribute corresponding source code.  (This alternative is\n"
                              _L_"    allowed only for noncommercial distribution and only if you\n"
                              _L_"    received the program in object code or executable form with such\n"
                              _L_"    an offer, in accord with Subsection b above.)\n"
                              _L_"\n"
                              _L_"The source code for a work means the preferred form of the work for\n"
                              _L_"making modifications to it.  For an executable work, complete source\n"
                              _L_"code means all the source code for all modules it contains, plus any\n"
                              _L_"associated interface definition files, plus the scripts used to\n"
                              _L_"control compilation and installation of the executable.  However, as a\n"
                              _L_"special exception, the source code distributed need not include\n"
                              _L_"anything that is normally distributed (in either source or binary\n"
                              _L_"form) with the major components (compiler, kernel, and so on) of the\n"
                              _L_"operating system on which the executable runs, unless that component\n"
                              _L_"itself accompanies the executable.\n"
                              _L_"\n"
                              _L_"If distribution of executable or object code is made by offering\n"
                              _L_"access to copy from a designated place, then offering equivalent\n"
                              _L_"access to copy the source code from the same place counts as\n"
                              _L_"distribution of the source code, even though third parties are not\n"
                              _L_"compelled to copy the source along with the object code.\n"
                              _L_"\n"
                              _L_"  4. You may not copy, modify, sublicense, or distribute the Program\n"
                              _L_"except as expressly provided under this License.  Any attempt\n"
                              _L_"otherwise to copy, modify, sublicense or distribute the Program is\n"
                              _L_"void, and will automatically terminate your rights under this License.\n"
                              _L_"However, parties who have received copies, or rights, from you under\n"
                              _L_"this License will not have their licenses terminated so long as such\n"
                              _L_"parties remain in full compliance.\n"
                              _L_"\n"
                              _L_"  5. You are not required to accept this License, since you have not\n"
                              _L_"signed it.  However, nothing else grants you permission to modify or\n"
                              _L_"distribute the Program or its derivative works.  These actions are\n"
                              _L_"prohibited by law if you do not accept this License.  Therefore, by\n"
                              _L_"modifying or distributing the Program (or any work based on the\n"
                              _L_"Program), you indicate your acceptance of this License to do so, and\n"
                              _L_"all its terms and conditions for copying, distributing or modifying\n"
                              _L_"the Program or works based on it.\n"
                              _L_"\n"
                              _L_"  6. Each time you redistribute the Program (or any work based on the\n"
                              _L_"Program), the recipient automatically receives a license from the\n"
                              _L_"original licensor to copy, distribute or modify the Program subject to\n"
                              _L_"these terms and conditions.  You may not impose any further\n"
                              _L_"restrictions on the recipients' exercise of the rights granted herein.\n"
                              _L_"You are not responsible for enforcing compliance by third parties to\n"
                              _L_"this License.\n"
                              _L_"\n"
                              _L_"  7. If, as a consequence of a court judgment or allegation of patent\n"
                              _L_"infringement or for any other reason (not limited to patent issues),\n"
                              _L_"conditions are imposed on you (whether by court order, agreement or\n"
                              _L_"otherwise) that contradict the conditions of this License, they do not\n"
                              _L_"excuse you from the conditions of this License.  If you cannot\n"
                              _L_"distribute so as to satisfy simultaneously your obligations under this\n"
                              _L_"License and any other pertinent obligations, then as a consequence you\n"
                              _L_"may not distribute the Program at all.  For example, if a patent\n"
                              _L_"license would not permit royalty-free redistribution of the Program by\n"
                              _L_"all those who receive copies directly or indirectly through you, then\n"
                              _L_"the only way you could satisfy both it and this License would be to\n"
                              _L_"refrain entirely from distribution of the Program.\n"
                              _L_"\n"
                              _L_"If any portion of this section is held invalid or unenforceable under\n"
                              _L_"any particular circumstance, the balance of the section is intended to\n"
                              _L_"apply and the section as a whole is intended to apply in other\n"
                              _L_"circumstances.\n"
                              _L_"\n"
                              _L_"It is not the purpose of this section to induce you to infringe any\n"
                              _L_"patents or other property right claims or to contest validity of any\n"
                              _L_"such claims; this section has the sole purpose of protecting the\n"
                              _L_"integrity of the free software distribution system, which is\n"
                              _L_"implemented by public license practices.  Many people have made\n"
                              _L_"generous contributions to the wide range of software distributed\n"
                              _L_"through that system in reliance on consistent application of that\n"
                              _L_"system; it is up to the author/donor to decide if he or she is willing\n"
                              _L_"to distribute software through any other system and a licensee cannot\n"
                              _L_"impose that choice.\n"
                              _L_"\n"
                              _L_"This section is intended to make thoroughly clear what is believed to\n"
                              _L_"be a consequence of the rest of this License.\n"
                              _L_"\n"
                              _L_"  8. If the distribution and/or use of the Program is restricted in\n"
                              _L_"certain countries either by patents or by copyrighted interfaces, the\n"
                              _L_"original copyright holder who places the Program under this License\n"
                              _L_"may add an explicit geographical distribution limitation excluding\n"
                              _L_"those countries, so that distribution is permitted only in or among\n"
                              _L_"countries not thus excluded.  In such case, this License incorporates\n"
                              _L_"the limitation as if written in the body of this License.\n"
                              _L_"\n"
                              _L_"  9. The Free Software Foundation may publish revised and/or new versions\n"
                              _L_"of the General Public License from time to time.  Such new versions will\n"
                              _L_"be similar in spirit to the present version, but may differ in detail to\n"
                              _L_"address new problems or concerns.\n"
                              _L_"\n"
                              _L_"Each version is given a distinguishing version number.  If the Program\n"
                              _L_"specifies a version number of this License which applies to it and \"any\n"
                              _L_"later version\", you have the option of following the terms and conditions\n"
                              _L_"either of that version or of any later version published by the Free\n"
                              _L_"Software Foundation.  If the Program does not specify a version number of\n"
                              _L_"this License, you may choose any version ever published by the Free Software\n"
                              _L_"Foundation.\n"
                              _L_"\n"
                              _L_"  10. If you wish to incorporate parts of the Program into other free\n"
                              _L_"programs whose distribution conditions are different, write to the author\n"
                              _L_"to ask for permission.  For software which is copyrighted by the Free\n"
                              _L_"Software Foundation, write to the Free Software Foundation; we sometimes\n"
                              _L_"make exceptions for this.  Our decision will be guided by the two goals\n"
                              _L_"of preserving the free status of all derivatives of our free software and\n"
                              _L_"of promoting the sharing and reuse of software generally.\n"
                              _L_"\n"
                              _L_"                NO WARRANTY\n"
                              _L_"\n"
                              _L_"  11. BECAUSE THE PROGRAM IS LICENSED FREE OF CHARGE, THERE IS NO WARRANTY\n"
                              _L_"FOR THE PROGRAM, TO THE EXTENT PERMITTED BY APPLICABLE LAW.  EXCEPT WHEN\n"
                              _L_"OTHERWISE STATED IN WRITING THE COPYRIGHT HOLDERS AND/OR OTHER PARTIES\n"
                              _L_"PROVIDE THE PROGRAM \"AS IS\" WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED\n"
                              _L_"OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF\n"
                              _L_"MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.  THE ENTIRE RISK AS\n"
                              _L_"TO THE QUALITY AND PERFORMANCE OF THE PROGRAM IS WITH YOU.  SHOULD THE\n"
                              _L_"PROGRAM PROVE DEFECTIVE, YOU ASSUME THE COST OF ALL NECESSARY SERVICING,\n"
                              _L_"REPAIR OR CORRECTION.\n"
                              _L_"\n"
                              _L_"  12. IN NO EVENT UNLESS REQUIRED BY APPLICABLE LAW OR AGREED TO IN WRITING\n"
                              _L_"WILL ANY COPYRIGHT HOLDER, OR ANY OTHER PARTY WHO MAY MODIFY AND/OR\n"
                              _L_"REDISTRIBUTE THE PROGRAM AS PERMITTED ABOVE, BE LIABLE TO YOU FOR DAMAGES,\n"
                              _L_"INCLUDING ANY GENERAL, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES ARISING\n"
                              _L_"OUT OF THE USE OR INABILITY TO USE THE PROGRAM (INCLUDING BUT NOT LIMITED\n"
                              _L_"TO LOSS OF DATA OR DATA BEING RENDERED INACCURATE OR LOSSES SUSTAINED BY\n"
                              _L_"YOU OR THIRD PARTIES OR A FAILURE OF THE PROGRAM TO OPERATE WITH ANY OTHER\n"
                              _L_"PROGRAMS), EVEN IF SUCH HOLDER OR OTHER PARTY HAS BEEN ADVISED OF THE\n"
                              _L_"POSSIBILITY OF SUCH DAMAGES.\n"
                              _L_"\n"
                              _L_"             END OF TERMS AND CONDITIONS\n"
                              _L_"\n"
                              _L_"        How to Apply These Terms to Your New Programs\n"
                              _L_"\n"
                              _L_"  If you develop a new program, and you want it to be of the greatest\n"
                              _L_"possible use to the public, the best way to achieve this is to make it\n"
                              _L_"free software which everyone can redistribute and change under these terms.\n"
                              _L_"\n"
                              _L_"  To do so, attach the following notices to the program.  It is safest\n"
                              _L_"to attach them to the start of each source file to most effectively\n"
                              _L_"convey the exclusion of warranty; and each file should have at least\n"
                              _L_"the \"copyright\" line and a pointer to where the full notice is found.\n"
                              _L_"\n"
                              _L_"    <one line to give the program's name and a brief idea of what it does.>\n"
                              _L_"    Copyright (C) <year>  <name of author>\n"
                              _L_"\n"
                              _L_"    This program is free software; you can redistribute it and/or modify\n"
                              _L_"    it under the terms of the GNU General Public License as published by\n"
                              _L_"    the Free Software Foundation; either version 2 of the License, or\n"
                              _L_"    (at your option) any later version.\n"
                              _L_"\n"
                              _L_"    This program is distributed in the hope that it will be useful,\n"
                              _L_"    but WITHOUT ANY WARRANTY; without even the implied warranty of\n"
                              _L_"    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\n"
                              _L_"    GNU General Public License for more details.\n"
                              _L_"\n"
                              _L_"    You should have received a copy of the GNU General Public License\n"
                              _L_"    along with this program; if not, write to the Free Software\n"
                              _L_"    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA\n"
                              _L_"\n"
                              _L_"\n"
                              _L_"Also add information on how to contact you by electronic and paper mail.\n"
                              _L_"\n"
                              _L_"If the program is interactive, make it output a short notice like this\n"
                              _L_"when it starts in an interactive mode:\n"
                              _L_"\n"
                              _L_"    Gnomovision version 69, Copyright (C) year name of author\n"
                              _L_"    Gnomovision comes with ABSOLUTELY NO WARRANTY; for details type `show w'.\n"
                              _L_"    This is free software, and you are welcome to redistribute it\n"
                              _L_"    under certain conditions; type `show c' for details.\n"
                              _L_"\n"
                              _L_"The hypothetical commands `show w' and `show c' should show the appropriate\n"
                              _L_"parts of the General Public License.  Of course, the commands you use may\n"
                              _L_"be called something other than `show w' and `show c'; they could even be\n"
                              _L_"mouse-clicks or menu items--whatever suits your program.\n"
                              _L_"\n"
                              _L_"You should also get your employer (if you work as a programmer) or your\n"
                              _L_"school, if any, to sign a \"copyright disclaimer\" for the program, if\n"
                              _L_"necessary.  Here is a sample; alter the names:\n"
                              _L_"\n"
                              _L_"  Yoyodyne, Inc., hereby disclaims all copyright interest in the program\n"
                              _L_"  `Gnomovision' (which makes passes at compilers) written by James Hacker.\n"
                              _L_"\n"
                              _L_"  <signature of Ty Coon>, 1 April 1989\n"
                              _L_"  Ty Coon, President of Vice\n"
                              _L_"\n"
                              _L_"This General Public License does not permit incorporating your program into\n"
                              _L_"proprietary programs.  If your program is a subroutine library, you may\n"
                              _L_"consider it more useful to permit linking proprietary applications with the\n"
                              _L_"library.  If this is what you want to do, use the GNU Library General\n"
                              _L_"Public License instead of this License.\n");

#endif
